service: shop-api

app: shop-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  profile: epam_bipin
  httpApi:
    cors: true
custom:
  autoswagger:
    title: Shop API
    apiType: httpApi
    generateSwaggerOnDeploy: true
    swaggerPath: "swagger"
    useStage: true
functions:
  productList:
    handler: src/handlers/productList.handler
    events:
      - httpApi:
          path: /products
          method: get
          responseData:
            200:
              description: "Products fetched successfully!"
              bodyType: "ProductsList"

  productById:
    handler: src/handlers/productById.handler
    events:
      - httpApi:
          path: /products/{id}
          method: get
          responseData:
            200:
              description: "Product found!"
              bodyType: "ProductById"
            404:
              description: "No such product found!"
              bodyType: "NotFound"

plugins:
  - serverless-auto-swagger
  - serverless-offline
