service: api

app: shop-api
frameworkVersion: "3"

custom:
  webpack:
    excludeFiles: "**/*.test.js"
    webpackConfig: "webpack.config.js"
    includeModules: false
    packager: "npm"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  profile: epam_bipin

package:
  individually: true
  excludeDevDependencies: false

functions:
  productList:
    handler: src/handlers/productList/index.js
    events:
      - httpApi:
          path: /products
          method: get
  productById:
    handler: src/handlers/productById/index.js
    events:
      - httpApi:
          path: /products/{id}
          method: get

plugins:
  - serverless-webpack
  - serverless-offline
