// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Shop API",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "productList",
        "description": "",
        "operationId": "productList.get./products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Products fetched successfully!",
            "schema": {
              "$ref": "#/definitions/ProductsList"
            }
          }
        }
      }
    },
    "/products/{id}": {
      "get": {
        "summary": "productById",
        "description": "",
        "operationId": "productById.get./products/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Product found!",
            "schema": {
              "$ref": "#/definitions/ProductById"
            }
          },
          "404": {
            "description": "No such product found!",
            "schema": {
              "$ref": "#/definitions/NotFound"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ProductsList": {
      "properties": {
        "message": {
          "title": "ProductsList.message",
          "type": "string"
        },
        "data": {
          "items": {
            "$ref": "#/definitions/Product"
          },
          "title": "ProductsList.data",
          "type": "array"
        }
      },
      "required": [
        "message",
        "data"
      ],
      "additionalProperties": false,
      "title": "ProductsList",
      "type": "object"
    },
    "ProductById": {
      "properties": {
        "message": {
          "title": "ProductById.message",
          "type": "string"
        },
        "data": {
          "$ref": "#/definitions/Product",
          "title": "ProductById.data"
        }
      },
      "required": [
        "message",
        "data"
      ],
      "additionalProperties": false,
      "title": "ProductById",
      "type": "object"
    },
    "NotFound": {
      "properties": {
        "message": {
          "title": "NotFound.message",
          "type": "string"
        },
        "data": {
          "title": "NotFound.data",
          "nullable": true
        }
      },
      "required": [
        "message",
        "data"
      ],
      "additionalProperties": false,
      "title": "NotFound",
      "type": "object"
    },
    "Product": {
      "properties": {
        "description": {
          "title": "Product.description",
          "type": "string"
        },
        "id": {
          "title": "Product.id",
          "type": "string"
        },
        "price": {
          "title": "Product.price",
          "type": "number"
        },
        "title": {
          "title": "Product.title",
          "type": "string"
        }
      },
      "required": [
        "description",
        "id",
        "price",
        "title"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};