service: import-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  profile: epam_bipin
  httpApi:
    cors: true
  environment:
    BUCKET_NAME: "cloud-course-epam-import-service-bucket"

functions:
  api:
    handler: src/handlers/importProductsFile/index.handler
    events:
      - httpApi:
          path: /import
          method: get

plugins:
  - serverless-offline
