service: import-service
frameworkVersion: "3"
app: import-service-api

custom:
  bucket: cloud-course-epam-import-service-bucket

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  profile: epam_bipin
  httpApi:
    cors: true
  environment:
    BUCKET_NAME: ${self:custom.bucket}

functions:
  importProductsFile:
    handler: src/handlers/importProductsFile/index.handler
    events:
      - httpApi:
          path: /import
          method: get
  importFileParser:
    handler: src/handlers/importFileParser/index.handler
    events:
      - s3:
          event: s3:ObjectCreated:*
          bucket: ${self:custom.bucket}
          rules:
            - prefix: uploaded/
          existing: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:GetObject
        Resource:
          - "arn:aws:s3:::${self:custom.bucket}/uploaded/*"

plugins:
  - serverless-offline
  - serverless-iam-roles-per-function
